name: Docker Container Build

on:
  push:
    branches: [ "main", "development" ]

jobs:
  build_env:
    name: Build Container ${{ github.ref_name }}
    runs-on: ubuntu-latest
    if: github.repository_owner == 'aau-cns'
    steps:
    - name: Debug Console
      env:
        TEST_VAR: "this is a test"
      run: >
           echo "Test output"
    - name: Output var
      run: >
           echo "Var: ${TEST_VAR}"
