name: Docker Container Build

on:
  push:
    branches: [ "main", "development" ]

jobs:
  build_env:
    name: Build Container ${{ github.ref_name }}
    runs-on: ubuntu-latest
    if: true
    steps:
    - name: Debug Console
      run: >
           echo "Test output"
